# Generated by Django 3.2.9 on 2021-11-26 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=100)),
                ('PatientEmail', models.EmailField(max_length=100)),
                ('PatientPhone', models.CharField(max_length=100)),
                ('PatientAge', models.IntegerField()),
                ('PatientGender', models.CharField(max_length=100)),
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
